
  # script:
    # - latexmk -pdf -shell-escape -bibtex phd-thesis.tex
    # - cp phd-thesis.pdf public/
    # - echo "Nothing to do"

pages:
  image: dsferruzza/latex
  artifacts:
    paths:
      - public/phd-thesis.pdf
  only:
    - master